language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-flask
# command to run tests
script:
  - python -m pytest
